name: Roach-Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17]

    steps:
    - uses: actions/checkout@v2
    - uses: ArtiomTr/jest-coverage-report-action@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        github-token: ${{ secrets.SECRET_TOKEN }}
        test-script: npm run test
        working-directory: ./test
        custom-title: Roach Unit Testing Reports
